### ISSUE TITLE
Compatibility with ELB2

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/elb-metrics#12]
ELB 2 / Application Load Balancing is a different namespace, and some of the metrics are named differently (ie "Latency" becomes "TargetResponseTime"). It would be great to be compatible with both versions of ELB. Can this be detected automatically, or passed as a flag, and the right metrics returned whether you're using classic ELB or ELB 2?

cc @aarthykc @yhahn

**Comment by yhahn** [comment]
https://github.com/mapbox/elb-metrics/pull/13
