### ISSUE TITLE
Add us-east-2

### ISSUE THREAD

**Issue by arunasank** [mapbox/elb-metrics#24]

**Comment by arunasank** [comment]
👋 @aarthyc need your help to publish this. 🙈

Next actions:
* [ ] Publish package to NPM - @aarthykc (I have bumped the version)
* [ ] Give access to the rest of the platform team to publish to this package. 💃 - @aarthykc

**Comment by aarthykc** [comment]
Done @arunasank !

**Comment by arunasank** [comment]
Thank youu!
