### ISSUE TITLE
input / output

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/elb-metrics#5]
Let's keep it simple in terms of what this tool provides:
- **Input**: the bare minimum [params you need](https://github.com/mapbox/elb-metrics/issues/2) to retrieve ELB metrics.
- **Output**: an object that provides a high-level overview of results.

------

Current bench provides a high level overview of the whole time period, like
```
### Bench (600s)

- requests:     225.2/s
- connect mean: 142.0ms
- finish mean:  142.1ms
- payload mean: 3315.2
- non 200/304:  1602 (1.2%)
- cacheHit:     0 (0.0%)
- cacheRefresh: 0 (0.0%)
- cacheMiss:    0 (0.0%)
- cacheUnknown: 135119 (100.0%)
```

I would like to see us do the same. How about we return 
- Time period (number of seconds)
- Average requests/second over the period
- Average latency over the period
- Percentage of total requests that were 2xx
- Percentage of total requests that were 3xx
- Percentage of total requests that were 4xx
- Percentage of total requests that were 5xx

-----

Here's an example of how I want to interact with this utility:

```js
test('give me metrics', function(assert) {
  var params = {
    start: 1471356157000,
    end: 1471356167000,
    elbName: 'my-elb',
    region: 'us-east-1'
  };

  elbMetrics(params, function(err, res) {
    assert.ifError(err);
    assert.deepEqual(res, {
      'period': '10s',
      'requests': '500/s',
      'mean latency': '100ms',
      '2xx': '67%',
      '3xx': '20%',
      '4xx': '10%',
      '5xx': '3%'
    });
    assert.end();
  });
});
```

The `elbMetrics` function will be doing more work behind the scenes, and should be comprised of other functions that we test individually:

1. take user parameters and combine them with other assumed parameters that we need to make a request to CloudWatch
2. make the request to CloudWatch
3. parse the results and do some math to find the averages/values we are interested in
4. prepare the final object based on those values ^ and return it

Even though there's a lot of different work to do, the idea is to expose a single function, `elbMetrics`, to the user.

@aarthykc do you feel 👍  about tackling each of those functions (and tests) separately and then putting them all together in a function like the test case above describes ?

**Comment by emilymcafee** [comment]
@aarthykc I think we're good to close here, yeah ?

**Comment by aarthykc** [comment]
Yes, closing !
